# Generated by Django 5.1.3 on 2024-11-18 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('min_age_in_months', models.IntegerField()),
                ('max_age_in_months', models.IntegerField()),
                ('display_age', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('amazon_link', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/properties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
