services:
  nginx:
    build: ./nginx
    ports: 
      - 1337:80
    depends_on:
      - web
    volumes:
      - ssl:/etc/nginx/ssl
      - media_volume:/usr/src/djangobnb_backend/media
  web:
    build: ./tnot_backend
    command: gunicorn tnot_backend.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./tnot_backend/:/usr/src/tnot_backend
      - media_volume:/usr/src/djangobnb_backend/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - daphne
  daphne:
    build: ./tnot_backend
    command: daphne --bind 0.0.0.0 -p 8002 tnot_backend.asgi:application
    ports:
      - 8002:8002 
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=tnot

volumes:
  postgres_data:
  media_volume: