services:
  nginx:
    build: ./nginx
    ports: 
      - 1337:80
      - 443:443
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/djangobnb_backend/media
      - static_volume:/home/tnot_backend/web/staticfiles
  web:
    build: 
      context: ./tnot_backend
      dockerfile: Dockerfile.prod
    command: gunicorn tnot_backend.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./tnot_backend/:/usr/src/tnot_backend
      - static_volume:/home/tnot_backend/web/staticfiles
      - media_volume:/usr/src/djangobnb_backend/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - daphne
  daphne:
    build: ./tnot_backend
    command: daphne --bind 0.0.0.0 -p 8002 tnot_backend.asgi:application
    ports:
      - 8002:8002 
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume:
  ssl_certs: