services:
  web:
    build: ./tnot_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./tnot_backend/:/usr/src/tnot_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=tnot_dev

volumes:
  postgres_data: